# Generated by Django 2.1.2 on 2018-11-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierno_char', models.CharField(max_length=30, null=True)),
                ('type_char', models.CharField(max_length=30, null=True)),
                ('size_char', models.CharField(max_length=20, null=True)),
                ('color_char', models.CharField(max_length=20, null=True)),
                ('price_number', models.IntegerField(default=0, null=True)),
                ('manu_char', models.CharField(max_length=30, null=True)),
                ('memo_text', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierno_char', models.CharField(max_length=30, null=True)),
                ('type_char', models.CharField(max_length=30, null=True)),
                ('size_char', models.CharField(max_length=20, null=True)),
                ('color_char', models.CharField(max_length=20, null=True)),
                ('price_number', models.IntegerField(default=0, null=True)),
                ('memo_text', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
