# Generated by Django 2.1.2 on 2018-11-07 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogoHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_char', models.CharField(max_length=30, null=True)),
                ('name_char', models.CharField(max_length=60, null=True)),
                ('location_char', models.CharField(max_length=80, null=True)),
                ('country_char', models.CharField(max_length=60, null=True)),
                ('contact_char', models.CharField(max_length=60, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='garments',
            name='supplierno_char',
        ),
        migrations.RemoveField(
            model_name='hats',
            name='supplierno_char',
        ),
        migrations.AddField(
            model_name='garments',
            name='suppliersno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LogoHome.Suppliers'),
        ),
        migrations.AddField(
            model_name='hats',
            name='suppliersno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LogoHome.Suppliers'),
        ),
    ]
